# 20 minutes to Julia

```{questions}

- What does the basic syntax of Julia look like?
- How does Julia handle types?
```

```{objectives}
- Get familiar with the basics of Julia in 20 minutes.
```

This section give a compact overview of the basic features
and syntax of Julia.

## Running Julia

After installing Julia, you can run Julia code in various ways:

1. [REPL](https://docs.julialang.org/en/v1/stdlib/REPL/)

   A REPL (read-evaluate-print loop) reads input, evaluates
   the expression, prints any output and then loops back.
   Julia's REPL is highly versatile and is useful for exploratory work.
   The Julia REPL has four modes:
   
     - **Julian mode** - default mode where prompt starts with ``julia>``.
       Here you enter Julia expressions and see output.       
     - Type ``?`` to go to **Help mode** where prompt starts with ``help?>``.
       Julia will print help/documentation on anything you enter.
     - Type ``;`` to go to **Shell mode** where prompt starts with
       ``shell>``. You can type any shell commands as you would from terminal.
     - Type ``]`` to go to **Package mode** where prompt starts with
       ``(@v1.5) pkg>`` (if you have Julia version 1.5). Here you can add
       packages with ``add`, update packages with ``update`` etc. To see
       all options type ``?``.
     - To exit any non-Julian mode, hit Escape key.
       
2. [Jupyter](https://jupyter.org/)

   Jupyter notebooks are familiar to many Python and R users. WRITEME

3. [Pluto.jl](https://github.com/fonsp/Pluto.jl)

   Pluto offers a similar notebook experience to Jupyter, but in contrast
   to Jupyter
   Pluto understands global references between cells, and
   reactively re-evaluates cells affected by a code change.

4. Juno or VSCode
   

```{callout}
   You can copy code cells below by pressing the button in the top right
   corner, and paste into the REPL, a notebook or and IDE.
```

## Fundamentals

### Variables

We only need to specify name and value of variables,
Julia figures out the type:

In [140]:
A = 3.14               # scalar, float
B = 100                # scalar, integer
S = "hello world"      # string
x = true;              # boolean. The semicolon suppresses output

To see the type of a variable use `typeof`:

In [142]:
typeof(A)

Float64

We can also use the `println` function along with the interpolation operator `$`:

In [32]:
println("A has type $(typeof(A))")
println("B has type $(typeof(B))")
println("C has type $(typeof(C))")
println("D has type $(typeof(D))")
println("E has type $(typeof(E))")
println("S has type $(typeof(S))")
println("x has type $(typeof(x))")

A has type Float64
B has type Int64
C has type Array{Int64,1}
D has type Array{Int64,2}
E has type Array{Int64,2}
S has type String
x has type Bool


We can also use UTF-8 symbols as well as LaTeX syntax for special characters (type e.g. `\alpha` and `TAB`)

In [146]:
😺 = "smiley_cat" 
typeof(😺)

String

In [1]:
α = 0.1

0.1

In [5]:
π # some are predefined

π = 3.1415926535897...

### Inf, NaN and nothing

In [39]:
1/0

Inf

In [43]:
-1/0

-Inf

In [47]:
100 - Inf

-Inf

In [45]:
0/0

NaN

`nothing` is used by convention when there is no value to return. The type of `nothing` is `Nothing`

In [55]:
n = nothing

In [57]:
println(n)

nothing


In [56]:
typeof(n)

Nothing

TODO: mention also overflow and BigInt?

### Arrays and other data structures

Arrays are created using the square brackets

In [13]:
a = [1, 2, 3, 4]

4-element Vector{Int64}:
 1
 2
 3
 4

Forcing a specific type

In [14]:
a = Float64[1,2,3,4]

4-element Vector{Float64}:
 1.0
 2.0
 3.0
 4.0

Using ranges to create arrays

In [84]:
a = [1:5;]    # note the semicolon

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

In [15]:
b = [range(0,stop=2π,length=5);]

5-element Vector{Float64}:
 0.0
 1.5707963267948966
 3.141592653589793
 4.71238898038469
 6.283185307179586

Without semicolon you get a 1-element array with a range 

In [97]:
a = [1:5]

1-element Array{UnitRange{Int64},1}:
 1:5

Special arrays

In [25]:
rand(5)                       # random length-5 array, uniform numbers in [0,1)
rand(Int, 5)                  # random length-5 array with integers
ones(5)                       # length-5 array with ones of type Float64 
zeros(5)                      # length-5 array with zeros of type Float64 

5-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0
 0.0

#### Indexing and slicing

In [118]:
a = [2, 1, 5, 4, 3]
a[1]     # indexing starts at 1

2

In [119]:
a[1:3]

3-element Array{Int64,1}:
 2
 1
 5

In [120]:
a[3:end]   # end represents the last index

3-element Array{Int64,1}:
 5
 4
 3

In [121]:
a[1:2:end]   # using a step size of 2

3-element Array{Int64,1}:
 2
 5
 3

#### Multidimensional arrays

In [17]:
matrix = [1 2; 3 4]

2×2 Matrix{Int64}:
 1  2
 3  4

In [27]:
rand(12,4)                    # random 12×4 array
zeros(4,4,4,4);               # 4x4 array with zeros of type Float

Methods for looking at array properties

In [30]:
length(a)
first(a)
last(a)
minimum(a)
maximum(a)
argmin(a)
argmax(a)
size(a)

(13,)

#### Manipulating arrays

In [20]:
push!(a, 10)   # exclamation mark in function names means they change their input argument in-place

6-element Vector{Float64}:
  1.0
  2.0
  3.0
  4.0
 10.0
 10.0

In [22]:
insert!(a, 1, 42)  # insert in given position

8-element Vector{Float64}:
 42.0
 42.0
  1.0
  2.0
  3.0
  4.0
 10.0
 10.0

In [24]:
append!(a, [100, 101]) # append another array to the end

13-element Vector{Float64}:
  42.0
  42.0
   1.0
   2.0
   3.0
   4.0
  10.0
  10.0
 100.0
 101.0
 102.0
 100.0
 101.0

#### Tuples 

In [111]:
tup = (1, 2, 3)  
typeof(tup)

Tuple{Int64,Int64,Int64}

Tuples are immutable

In [112]:
tup[1] = 0

LoadError: MethodError: no method matching setindex!(::Tuple{Int64,Int64,Int64}, ::Int64, ::Int64)

#### Dictionaries

In [125]:
d = Dict([("A", 1), ("B", 2)])
# d = Dict("A"=>1, "B"=>2)    # alternative syntax

Dict{String,Int64} with 2 entries:
  "B" => 2
  "A" => 1

## Types

### Primitive and abstract types
- Numeric types, that represent numbers
    - `Number`
        - `Real` (example: `a::Real`)
        - `Integer` (example: `b::Int`)
            - `Int16`, `Int32`, `Int64`,..., `UInt64`
        - `AbstractFloat` 
            - `Float16`, `Float32`,`Float64`,...
- Strings (`String`, `Char`,...)
- `Bool` is a data type that can be either `true` or `false`.

### Composite types
- `complex` (`Complex{Int64}`,...) with `1 + 0.1im`
- Arrays (`Array{Int64,1}`,...)
- Mappings
    - `Dict`: a dictionary, also called a hashmap (`Dict{String,Int64}`,...)



- booleans, numbers (int, float), strings and chars
- vectors, matrices
- tuples, named tuples
- dictionaries
- composite types - structs
- abstract types - e.g. supertype(Float64)
     

Above we have seen examples of variables with types Float64, Int64, String, Bool and Nothing.

## Loops and conditionals

- for, if-else, while,
- iterators

In [70]:
for i in [1,2,3,4,5]
    println(i)
end

1
2
3
4
5


## Functions

- named and anonymous functions
- optional arguments
- keyword arguments
- multiple dispatch
- splatting

## Exception handling

Exceptions are thrown when an unexpected condition has occurred

In [130]:
sqrt(-1)

LoadError: DomainError with -1.0:
sqrt will only return a complex result if called with a complex argument. Try sqrt(Complex(x)).

Handle exceptions with a try/catch block

In [133]:
try
    sqrt(-1)
catch e
    println("caught it $e")
end

caught it DomainError(-1.0, "sqrt will only return a complex result if called with a complex argument. Try sqrt(Complex(x)).")


Exceptions can be created explicitly with `throw`

In [137]:
function myExp(x)
    if x>=0
        return exp(-x)
    else
        throw(DomainError(x, "argument must be non-negative"))
    end
end

myExp (generic function with 1 method)

In [138]:
myExp(1.0)

0.36787944117144233

In [139]:
myExp(-1.0)

LoadError: DomainError with -1.0:
argument must be non-negative

## Packages

## REPL and IDEs

A REPL (read-evaluate-print loop) reads input, evaluates
the expression, prints any output and then loops back.
Julia's REPL is highly versatile:

- Pluto.jl
- Weave.jl
- Jupyter  
  

## Style conventions

- Names of variables are in lower case.
- Word separation can be indicated by underscores ('_'), but use of underscores is discouraged unless the name would be hard to read otherwise.
- Names of Types and Modules begin with a capital letter and word separation is shown with upper camel case instead of underscores.
- Names of functions and macros are in lower case, without underscores.
- Functions that write to their arguments have names that end in !. These are sometimes called "mutat- ing" or "in-place" functions because they are intended to produce changes in their arguments after the function is called, not just return a value.

## See also

- [Learn X in Y minutes (Where X = Julia)](https://learnxinyminutes.com/docs/julia/)
- Berhane, Fisseha. (2019) R vs Julia Cheatsheet. Available at:
  https://datascience-enthusiast.com/R/R_Julia_cheat_sheet.html. (Accessed
  December 21, 2019).
- (2019) The Fast Track to Julia. Available at:
  https://juliadocs.github.io/Julia-Cheat-Sheet/. (Accessed December
  21, 2019).
- Gregory, Victoria, Andrij Stachurski, and Natasha Watkins. (2017a)
  Julia Cheatsheet. Available at:
  https://cheatsheets.quantecon.org/julia-cheatsheet.html. (Accessed
  December 21, 2019).
- Gregory, Victoria, Andrij Stachurski, and Natasha Watkins. (2017b)
  MATLAB–Python–Julia Cheatsheet. Available at:
  https://cheatsheets.quantecon.org/. (Accessed December 21, 2019).
- Johnson, Steven G. (2017) Julia & IJulia Cheat-Sheet (for 18.Xxx at
  MIT). Available at:
  http://math.mit.edu/%7Estevenj/Julia-cheatsheet.pdf. (Accessed
  December 21, 2019).
- Bezanson, Jeff, Stefan Karpinski, Viral Shah, and Alan
  Edelman. (2020) The Julia Language. The Julia Project. Available at:
  https://raw.githubusercontent.com/JuliaLang/docs.julialang.org/assets/julia-1.5.3.pdf.